apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-argocd-fundamentals
spec:
  title: Argo CD Fundamentals
  description: A workshop on learning the fundamentals of Argo CD
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/danielhelfand/lab-argocd-fundamentals
  content:
    image: danielhelfand/lab-argocd-fundamentals:latest
  session:
    env:
    - name: ARGOCD_SERVER_PASSWORD
      value: REPLACE_PASSWORD
    - name: ARGOCD_SERVER_ENDPOINT
      value: REPLACE_ENDPOINT
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: false
      editor:
        enabled: false
